name: 'Generate module'
description: 'Generate a Zikula module from a ModuleStudio application model'
inputs:
  model-name:
    description: 'Model name'
    required: true
    default: 'AcmeNews.mostapp'
  module-name:
    description: 'Module name'
    required: true
    default: 'Acme/NewsModule'
  base-dir:
    description: 'Path to the directory containing the modules folder (including trailing slash)'
    required: false
  verbose:
    description: 'Enable verbose output'
    required: false
outputs:
  result:
    description: 'Generated files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model-name }}
    - ${{ inputs.module-name }}
branding:
  icon: 'check'
  color: 'orange'
